(function () {
  "use strict";
  // Generated by build.py — edit property.json / company.json instead.
  window.__BRAND__ = {
  "name": "Eagle RE Properties, LLC",
  "contactName": "Steven",
  "property": {
    "address": "8367 Tamarack Dr, Florence, KY 41042",
    "beds": 3,
    "baths": 2,
    "sqft": 1211,
    "yearBuilt": 1985,
    "lotAcres": 0.3
  },
  "offer": {
    "mode": "web3forms",
    "endpoint": "https://api.web3forms.com/submit",
    "accessKey": "PASTE_YOUR_WEB3FORMS_ACCESS_KEY_HERE"
  },
  "contact": {
    "phone": "",
    "email": ""
  }
};
})();
